services:
  database:
    container_name: ${APP_NAME}-database
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - database:/var/lib/postgresql/data
      
  # app:
  #   container_name: ${APP_NAME}-app
  #   build:
  #     context: ../..
  #     dockerfile: apps/${APP_NAME}/Dockerfile
  #     args:
  #       APP_NAME: ${APP_NAME}
  #   restart: on-failure
  #   env_file:
  #     - ./.env
  #   ports:
  #     - '${APP_PORT}:${APP_PORT}'
  #   depends_on:
  #     - database

volumes:
  database:
    driver: local
