name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      users: ${{ steps.filter.outputs.users }}
      posts: ${{ steps.filter.outputs.posts }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            users:
              - 'apps/users/**'
              - 'libs/common/**'
              - 'libs/prisma/**'
              - 'libs/kafka/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'tsconfig.json'
              - 'tsconfig.build.json'
              - 'nest-cli.json'
              - 'scripts/**'
              - '.github/workflows/unit-tests.yml'
            posts:
              - 'apps/posts/**'
              - 'libs/common/**'
              - 'libs/prisma/**'
              - 'libs/kafka/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'tsconfig.json'
              - 'tsconfig.build.json'
              - 'nest-cli.json'
              - 'scripts/**'
              - '.github/workflows/unit-tests.yml'

  test-users:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.users == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: chmod -R +x ./scripts
      - run: pnpm run database:generate users
      - run: pnpm run test users

  test-posts:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.posts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: chmod -R +x ./scripts
      - run: pnpm run database:generate posts
      - run: pnpm run test posts
